# Generated by Django 5.1 on 2024-09-07 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_complete', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('phone_number', models.CharField()),
                ('is_designer', models.BooleanField(default=False)),
                ('is_costumer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
            ],
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('biografia', models.TextField()),
                ('social_media', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('specialty', models.CharField(max_length=200)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('User.user',),
        ),
    ]
