# Generated by Django 5.1 on 2024-09-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
