# Generated by Django 5.1 on 2024-08-31 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('Item_carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Cart.carrito')),
                ('Items', models.IntegerField(default=0)),
            ],
        ),
    ]
